### ISSUE TITLE
[BUG]Table headers are not centered

### ISSUE THREAD

**Issue by beierzhijin** [mgmeyers/obsidian-california-coast-theme#105]
Left-aligned and right-aligned are in effect, but there is a problem with centering alignment. I'm using the Advanced Tables plugin.
![image](https://user-images.githubusercontent.com/54610243/147197466-12529940-3633-4b98-85ad-93a55760d5a0.png)
------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/54610243/147197488-2f417fff-dd52-474d-b477-e7a9aa2112f0.png)

The default theme is normal.
![image](https://user-images.githubusercontent.com/54610243/147197920-6cd7d6a3-531d-4cb2-8c4b-c9fc082a623f.png)

**Comment by beierzhijin** [comment]
obsidian version :  The latest version - v0.13.14

**Comment by beierzhijin** [comment]
I have solved the problem.  This line of `th` needs to be commented out
```css
.markdown-preview-view th {
  background-color: var(--shade-2);
  font-weight: 500;
  /* text-align: left; */
}
```

p.s. I'm using the Advanced Tables plugin.
