### ISSUE TITLE
External link icon padding

### ISSUE THREAD

**Issue by agentcooper** [mgmeyers/obsidian-california-coast-theme#113]
Hey, thanks for the great theme!

It seems that there is an extra padding for the external link icon.

California Coast theme:
<img width="961" alt="california-coast" src="https://user-images.githubusercontent.com/794591/148550926-7290ae7b-9e53-4d4e-9fb2-e72a73a44143.png">

Default theme:
<img width="961" alt="default" src="https://user-images.githubusercontent.com/794591/148550936-e5ef5b38-c637-4fa8-b327-35785f105623.png">

I've fixed it with:
```css
.markdown-source-view.mod-cm6.cm-s-obsidian span.cm-formatting-link-string.cm-url.cm-string {
  padding: 0;
}
```
