### ISSUE TITLE
Todo checkboxes get cut off when transcluding them with seamless embed

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-california-coast-theme#67]
Hi, todo checkboxes get cut off when transcluding them with seamless embed.
<img width="143" alt="Screencapture 2021-04-19 at 10 07 13@2x" src="https://user-images.githubusercontent.com/4502360/115204328-a83f8200-a0f8-11eb-8846-a83a7530738b.png">

**Comment by mgmeyers** [comment]
@janpeeters70 Can you try downloading the theme again? I made some updates recently that should hopefully fix this

**Comment by janpeeters70** [comment]
Hi, I redownloaded the theme but no changes. Double-checked by deactivating all plugins and custom CSS but it stayed the same.

**Comment by janpeeters70** [comment]
Hi, I redownloaded the theme but no changes. Double-checked by deactivating all plugins and custom CSS, but it stayed the same. I just realized though that the checkboxes look like default system checkboxes, so maybe macOS is creating the problem?

**Comment by janpeeters70** [comment]
I got it fixed with this code, the problem was in the margin-left value.
maybe it's of help:

```css
.markdown-preview-view .task-list-item-checkbox {
  width: 14px; /* original value was 16px but I found this more fitting */
  height: 14px; /* original value was 16px but I found this more fitting */
  position: relative;
  line-height: 0;
  margin-left: -1em; /* original value was -1.2em, -.2 too much */
  margin-right: 8px;
  filter: none;
  margin-bottom: 0;
  top: 1px;
}
```
