### ISSUE TITLE
Checkbox spacing in edit mode

### ISSUE THREAD

**Issue by Mpic** [mgmeyers/obsidian-california-coast-theme#79]
On Linux as on Windows, the space between a `- [ ]` checkbox and the text following it is too small, it shows as if there was no space  typed (but there is) : 

![image](https://user-images.githubusercontent.com/5664276/117822999-4d1f2c00-b26d-11eb-80e9-9867438e4594.png)

This is better if I change the monospace font to a not-monospaced font, but I want to keep a monospaced font functional to be able to use tables comfortably for example.
Example when I change the monospace font in Style Settings to sans-serif : 

![image](https://user-images.githubusercontent.com/5664276/117823452-c4ed5680-b26d-11eb-9434-ec4015509036.png)

**Comment by liamcain** [comment]
Issue is caused by this line:

https://github.com/mgmeyers/obsidian-california-coast-theme/blob/18736e787d47e8734f9d1d02d3d4357c26532a25/src/020-document.css#L206

Seems like it should just be removed?

**Comment by Mpic** [comment]
Thanks ! I tested with Fira Mono and Ubuntu Mono and they seem to require different settings of `width` and `font-weight` so I made myself a CSS snippet to override these in the meantime : 

```css
.cm-s-obsidian span.cm-formatting-task {
  font-weight: 300; /* 300 for Fira Mono, 500 for Ubuntu Mono */
  width: 1.8em; /* 1.8 for Fira Mono, 1.5 for Ubuntu Mono */
}

```
