### ISSUE TITLE
Could the hierarchy of this sequence be adjusted more clearly? 

### ISSUE THREAD

**Issue by zhl111** [mgmeyers/obsidian-california-coast-theme#99]
![image](https://user-images.githubusercontent.com/29135984/139040095-387af2a5-c073-4384-a356-1e20e410419e.png)
like this
![548b414c2d165bf6c84022ab93caa62](https://user-images.githubusercontent.com/29135984/139040496-f4f7ea60-07fc-4913-a18e-47c6db2eabe4.png)

**Comment by mgmeyers** [comment]
@zhl111 To accomplish this, you'd have to remove the spacing from list elements entirely:

```css
.markdown-preview-view ol,
.markdown-preview-view ul { margin-bottom: 0 !important; }
```

But it shouldn't be as severe of an issue in the latest version of the theme.
